/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {ConsensusLevel, Decision, GameAnalysis, GameState, Guess, GuessDiscussion, MetaDecision, Resume, Risk, SpymasterClue} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  env?: Record<string, string | undefined>
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeClue(
      clue: SpymasterClue,state: GameState,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "AnalyzeClue",
        {
          "clue": clue,"state": state
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ContinueDiscussion(
      state: GameState,clue: SpymasterClue,currentDiscussion: GuessDiscussion,participantId: string,participantRole: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ContinueDiscussion",
        {
          "state": state,"clue": clue,"currentDiscussion": currentDiscussion,"participantId": participantId,"participantRole": participantRole
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DetermineNextAction(
      state: GameState,currentClue: SpymasterClue,previousGuesses: Guess[],currentDiscussion: GuessDiscussion,consensus: ConsensusLevel,guessesLeft: number,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "DetermineNextAction",
        {
          "state": state,"currentClue": currentClue,"previousGuesses": previousGuesses,"currentDiscussion": currentDiscussion,"consensus": consensus,"guessesLeft": guessesLeft
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExecuteGuess(
      state: GameState,clue: SpymasterClue,finalGuess: Guess,currentDiscussion: GuessDiscussion,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ExecuteGuess",
        {
          "state": state,"clue": clue,"finalGuess": finalGuess,"currentDiscussion": currentDiscussion
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      resume: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ExtractResume",
        {
          "resume": resume
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FinalizeGuess(
      state: GameState,discussion: GuessDiscussion,clue: SpymasterClue,currentRound: number,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "FinalizeGuess",
        {
          "state": state,"discussion": discussion,"clue": clue,"currentRound": currentRound
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateClue(
      state: GameState,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "GenerateClue",
        {
          "state": state
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ValidateGuess(
      guess: Guess,clue: SpymasterClue,state: GameState,discussion: GuessDiscussion,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ValidateGuess",
        {
          "guess": guess,"clue": clue,"state": state,"discussion": discussion
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  AnalyzeClue(
      clue: SpymasterClue,state: GameState,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "AnalyzeClue",
        {
          "clue": clue,"state": state
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ContinueDiscussion(
      state: GameState,clue: SpymasterClue,currentDiscussion: GuessDiscussion,participantId: string,participantRole: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ContinueDiscussion",
        {
          "state": state,"clue": clue,"currentDiscussion": currentDiscussion,"participantId": participantId,"participantRole": participantRole
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DetermineNextAction(
      state: GameState,currentClue: SpymasterClue,previousGuesses: Guess[],currentDiscussion: GuessDiscussion,consensus: ConsensusLevel,guessesLeft: number,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "DetermineNextAction",
        {
          "state": state,"currentClue": currentClue,"previousGuesses": previousGuesses,"currentDiscussion": currentDiscussion,"consensus": consensus,"guessesLeft": guessesLeft
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExecuteGuess(
      state: GameState,clue: SpymasterClue,finalGuess: Guess,currentDiscussion: GuessDiscussion,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ExecuteGuess",
        {
          "state": state,"clue": clue,"finalGuess": finalGuess,"currentDiscussion": currentDiscussion
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      resume: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ExtractResume",
        {
          "resume": resume
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  FinalizeGuess(
      state: GameState,discussion: GuessDiscussion,clue: SpymasterClue,currentRound: number,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "FinalizeGuess",
        {
          "state": state,"discussion": discussion,"clue": clue,"currentRound": currentRound
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateClue(
      state: GameState,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "GenerateClue",
        {
          "state": state
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ValidateGuess(
      guess: Guess,clue: SpymasterClue,state: GameState,discussion: GuessDiscussion,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      const env = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      return this.runtime.buildRequestSync(
        "ValidateGuess",
        {
          "guess": guess,"clue": clue,"state": state,"discussion": discussion
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
        env,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}