/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, ClientRegistry } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type * as types from "./types"
import type {ConsensusLevel, Decision, GameAnalysis, GameState, Guess, GuessDiscussion, MetaDecision, Resume, Risk, SpymasterClue} from "./types"
import type TypeBuilder from "./type_builder"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

export class BamlSyncClient {

  constructor(private runtime: BamlRuntime, private ctx_manager: BamlCtxManager) {}

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  
  AnalyzeClue(
      clue: SpymasterClue,state: GameState,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): GameAnalysis {
    try {
    const raw = this.runtime.callFunctionSync(
      "AnalyzeClue",
      {
        "clue": clue,"state": state
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as GameAnalysis
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  DetermineNextAction(
      state: GameState,currentClue: SpymasterClue,previousGuesses: Guess[],previousDiscussion: GuessDiscussion,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): MetaDecision {
    try {
    const raw = this.runtime.callFunctionSync(
      "DetermineNextAction",
      {
        "state": state,"currentClue": currentClue,"previousGuesses": previousGuesses,"previousDiscussion": previousDiscussion
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as MetaDecision
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      resume: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Resume {
    try {
    const raw = this.runtime.callFunctionSync(
      "ExtractResume",
      {
        "resume": resume
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as Resume
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  FinalizeGuess(
      state: GameState,discussion: GuessDiscussion,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Guess {
    try {
    const raw = this.runtime.callFunctionSync(
      "FinalizeGuess",
      {
        "state": state,"discussion": discussion
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as Guess
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  GenerateClue(
      state: GameState,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): SpymasterClue {
    try {
    const raw = this.runtime.callFunctionSync(
      "GenerateClue",
      {
        "state": state
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as SpymasterClue
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ValidateGuess(
      guess: Guess,clue: SpymasterClue,state: GameState,discussion: GuessDiscussion,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): GameAnalysis {
    try {
    const raw = this.runtime.callFunctionSync(
      "ValidateGuess",
      {
        "guess": guess,"clue": clue,"state": state,"discussion": discussion
      },
      this.ctx_manager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __baml_options__?.clientRegistry,
    )
    return raw.parsed(false) as GameAnalysis
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)