/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}


export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ConsensusLevel {
  High = "High",
  Medium = "Medium",
  Low = "Low",
}

export enum Decision {
  Continue = "Continue",
  ContunueWait = "ContunueWait",
  EndTurn = "EndTurn",
}

export enum Risk {
  High = "High",
  Medium = "Medium",
  Low = "Low",
}

export interface GameAnalysis {
  message: string
  suggestedMoves: Guess[]
  
}

export interface GameState {
  currentTeam: "red" | "blue"
  words: string[]
  teamWords: string[]
  opposingWords: string[]
  assassinWord: string
  revealedCards: string[]
  
}

export interface Guess {
  word: string
  reasoning: string
  discussion: string
  risk: Risk
  
}

export interface GuessDiscussion {
  candidateGuesses: Guess[]
  discussionLog: string[]
  conversationRounds: number
  participantContributions: Record<string, number>
  consensusReached: boolean
  consensusLevel: ConsensusLevel
  suggestedAction: Decision
  
}

export interface MetaDecision {
  decision: Decision
  reasoning: string[]
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface SpymasterClue {
  word: string
  number: number
  reasoning: string
  
}
